/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines CommandWaitingType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommandWaitingType
    {
        /// <summary>
        /// Enum ALLCOMPLETED for value: ALL_COMPLETED
        /// </summary>
        [EnumMember(Value = "ALL_COMPLETED")]
        ALLCOMPLETED = 1,

        /// <summary>
        /// Enum ANYCOMPLETED for value: ANY_COMPLETED
        /// </summary>
        [EnumMember(Value = "ANY_COMPLETED")]
        ANYCOMPLETED = 2,

        /// <summary>
        /// Enum ANYCOMBINATIONCOMPLETED for value: ANY_COMBINATION_COMPLETED
        /// </summary>
        [EnumMember(Value = "ANY_COMBINATION_COMPLETED")]
        ANYCOMBINATIONCOMPLETED = 3
    }

}
