/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Context
    /// </summary>
    [DataContract(Name = "Context")]
    public partial class Context : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Context" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Context() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Context" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId (required).</param>
        /// <param name="workflowStartedTimestamp">workflowStartedTimestamp (required).</param>
        /// <param name="stateExecutionId">stateExecutionId.</param>
        /// <param name="firstAttemptTimestamp">firstAttemptTimestamp.</param>
        /// <param name="attempt">attempt.</param>
        public Context(string workflowId = default(string), string workflowRunId = default(string), long workflowStartedTimestamp = default(long), string stateExecutionId = default(string), long firstAttemptTimestamp = default(long), int attempt = default(int))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for Context and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "workflowRunId" is required (not null)
            if (workflowRunId == null)
            {
                throw new ArgumentNullException("workflowRunId is a required property for Context and cannot be null");
            }
            this.WorkflowRunId = workflowRunId;
            this.WorkflowStartedTimestamp = workflowStartedTimestamp;
            this.StateExecutionId = stateExecutionId;
            this.FirstAttemptTimestamp = firstAttemptTimestamp;
            this.Attempt = attempt;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowStartedTimestamp
        /// </summary>
        [DataMember(Name = "workflowStartedTimestamp", IsRequired = true, EmitDefaultValue = true)]
        public long WorkflowStartedTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets StateExecutionId
        /// </summary>
        [DataMember(Name = "stateExecutionId", EmitDefaultValue = false)]
        public string StateExecutionId { get; set; }

        /// <summary>
        /// Gets or Sets FirstAttemptTimestamp
        /// </summary>
        [DataMember(Name = "firstAttemptTimestamp", EmitDefaultValue = false)]
        public long FirstAttemptTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets Attempt
        /// </summary>
        [DataMember(Name = "attempt", EmitDefaultValue = false)]
        public int Attempt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Context {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  WorkflowStartedTimestamp: ").Append(WorkflowStartedTimestamp).Append("\n");
            sb.Append("  StateExecutionId: ").Append(StateExecutionId).Append("\n");
            sb.Append("  FirstAttemptTimestamp: ").Append(FirstAttemptTimestamp).Append("\n");
            sb.Append("  Attempt: ").Append(Attempt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
