/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines ErrorSubStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorSubStatus
    {
        /// <summary>
        /// Enum UNCATEGORIZEDSUBSTATUS for value: UNCATEGORIZED_SUB_STATUS
        /// </summary>
        [EnumMember(Value = "UNCATEGORIZED_SUB_STATUS")]
        UNCATEGORIZEDSUBSTATUS = 1,

        /// <summary>
        /// Enum WORKFLOWALREADYSTARTEDSUBSTATUS for value: WORKFLOW_ALREADY_STARTED_SUB_STATUS
        /// </summary>
        [EnumMember(Value = "WORKFLOW_ALREADY_STARTED_SUB_STATUS")]
        WORKFLOWALREADYSTARTEDSUBSTATUS = 2,

        /// <summary>
        /// Enum WORKFLOWNOTEXISTSSUBSTATUS for value: WORKFLOW_NOT_EXISTS_SUB_STATUS
        /// </summary>
        [EnumMember(Value = "WORKFLOW_NOT_EXISTS_SUB_STATUS")]
        WORKFLOWNOTEXISTSSUBSTATUS = 3,

        /// <summary>
        /// Enum WORKERAPIERROR for value: WORKER_API_ERROR
        /// </summary>
        [EnumMember(Value = "WORKER_API_ERROR")]
        WORKERAPIERROR = 4,

        /// <summary>
        /// Enum LONGPOLLTIMEOUTSUBSTATUS for value: LONG_POLL_TIME_OUT_SUB_STATUS
        /// </summary>
        [EnumMember(Value = "LONG_POLL_TIME_OUT_SUB_STATUS")]
        LONGPOLLTIMEOUTSUBSTATUS = 5
    }

}
