/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines ExecutingStateIdMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExecutingStateIdMode
    {
        /// <summary>
        /// Enum ENABLEDFORALL for value: ENABLED_FOR_ALL
        /// </summary>
        [EnumMember(Value = "ENABLED_FOR_ALL")]
        ENABLEDFORALL = 1,

        /// <summary>
        /// Enum ENABLEDFORSTATESWITHWAITUNTIL for value: ENABLED_FOR_STATES_WITH_WAIT_UNTIL
        /// </summary>
        [EnumMember(Value = "ENABLED_FOR_STATES_WITH_WAIT_UNTIL")]
        ENABLEDFORSTATESWITHWAITUNTIL = 2,

        /// <summary>
        /// Enum DISABLED for value: DISABLED
        /// </summary>
        [EnumMember(Value = "DISABLED")]
        DISABLED = 3
    }

}
