/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines ExecuteApiFailurePolicy
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExecuteApiFailurePolicy
    {
        /// <summary>
        /// Enum FAILWORKFLOWONEXECUTEAPIFAILURE for value: FAIL_WORKFLOW_ON_EXECUTE_API_FAILURE
        /// </summary>
        [EnumMember(Value = "FAIL_WORKFLOW_ON_EXECUTE_API_FAILURE")]
        FAILWORKFLOWONEXECUTEAPIFAILURE = 1,

        /// <summary>
        /// Enum PROCEEDTOCONFIGUREDSTATE for value: PROCEED_TO_CONFIGURED_STATE
        /// </summary>
        [EnumMember(Value = "PROCEED_TO_CONFIGURED_STATE")]
        PROCEEDTOCONFIGUREDSTATE = 2
    }

}
