/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines IDReusePolicy
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IDReusePolicy
    {
        /// <summary>
        /// Enum ALLOWIFPREVIOUSEXITSABNORMALLY for value: ALLOW_IF_PREVIOUS_EXITS_ABNORMALLY
        /// </summary>
        [EnumMember(Value = "ALLOW_IF_PREVIOUS_EXITS_ABNORMALLY")]
        ALLOWIFPREVIOUSEXITSABNORMALLY = 1,

        /// <summary>
        /// Enum ALLOWIFNORUNNING for value: ALLOW_IF_NO_RUNNING
        /// </summary>
        [EnumMember(Value = "ALLOW_IF_NO_RUNNING")]
        ALLOWIFNORUNNING = 2,

        /// <summary>
        /// Enum DISALLOWREUSE for value: DISALLOW_REUSE
        /// </summary>
        [EnumMember(Value = "DISALLOW_REUSE")]
        DISALLOWREUSE = 3,

        /// <summary>
        /// Enum ALLOWTERMINATEIFRUNNING for value: ALLOW_TERMINATE_IF_RUNNING
        /// </summary>
        [EnumMember(Value = "ALLOW_TERMINATE_IF_RUNNING")]
        ALLOWTERMINATEIFRUNNING = 4
    }

}
