/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// InterStateChannelCommand
    /// </summary>
    [DataContract(Name = "InterStateChannelCommand")]
    public partial class InterStateChannelCommand : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterStateChannelCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InterStateChannelCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InterStateChannelCommand" /> class.
        /// </summary>
        /// <param name="commandId">commandId.</param>
        /// <param name="channelName">channelName (required).</param>
        /// <param name="atLeast">atLeast.</param>
        /// <param name="atMost">atMost.</param>
        public InterStateChannelCommand(string commandId = default(string), string channelName = default(string), int atLeast = default(int), int atMost = default(int))
        {
            // to ensure "channelName" is required (not null)
            if (channelName == null)
            {
                throw new ArgumentNullException("channelName is a required property for InterStateChannelCommand and cannot be null");
            }
            this.ChannelName = channelName;
            this.CommandId = commandId;
            this.AtLeast = atLeast;
            this.AtMost = atMost;
        }

        /// <summary>
        /// Gets or Sets CommandId
        /// </summary>
        [DataMember(Name = "commandId", EmitDefaultValue = false)]
        public string CommandId { get; set; }

        /// <summary>
        /// Gets or Sets ChannelName
        /// </summary>
        [DataMember(Name = "channelName", IsRequired = true, EmitDefaultValue = true)]
        public string ChannelName { get; set; }

        /// <summary>
        /// Gets or Sets AtLeast
        /// </summary>
        [DataMember(Name = "atLeast", EmitDefaultValue = false)]
        public int AtLeast { get; set; }

        /// <summary>
        /// Gets or Sets AtMost
        /// </summary>
        [DataMember(Name = "atMost", EmitDefaultValue = false)]
        public int AtMost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InterStateChannelCommand {\n");
            sb.Append("  CommandId: ").Append(CommandId).Append("\n");
            sb.Append("  ChannelName: ").Append(ChannelName).Append("\n");
            sb.Append("  AtLeast: ").Append(AtLeast).Append("\n");
            sb.Append("  AtMost: ").Append(AtMost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
