/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// InterStateChannelPublishing
    /// </summary>
    [DataContract(Name = "InterStateChannelPublishing")]
    public partial class InterStateChannelPublishing : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterStateChannelPublishing" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InterStateChannelPublishing() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InterStateChannelPublishing" /> class.
        /// </summary>
        /// <param name="channelName">channelName (required).</param>
        /// <param name="value">value.</param>
        public InterStateChannelPublishing(string channelName = default(string), EncodedObject value = default(EncodedObject))
        {
            // to ensure "channelName" is required (not null)
            if (channelName == null)
            {
                throw new ArgumentNullException("channelName is a required property for InterStateChannelPublishing and cannot be null");
            }
            this.ChannelName = channelName;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets ChannelName
        /// </summary>
        [DataMember(Name = "channelName", IsRequired = true, EmitDefaultValue = true)]
        public string ChannelName { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public EncodedObject Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InterStateChannelPublishing {\n");
            sb.Append("  ChannelName: ").Append(ChannelName).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
