/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines SearchAttributeValueType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SearchAttributeValueType
    {
        /// <summary>
        /// Enum KEYWORD for value: KEYWORD
        /// </summary>
        [EnumMember(Value = "KEYWORD")]
        KEYWORD = 1,

        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 2,

        /// <summary>
        /// Enum DATETIME for value: DATETIME
        /// </summary>
        [EnumMember(Value = "DATETIME")]
        DATETIME = 3,

        /// <summary>
        /// Enum INT for value: INT
        /// </summary>
        [EnumMember(Value = "INT")]
        INT = 4,

        /// <summary>
        /// Enum DOUBLE for value: DOUBLE
        /// </summary>
        [EnumMember(Value = "DOUBLE")]
        DOUBLE = 5,

        /// <summary>
        /// Enum BOOL for value: BOOL
        /// </summary>
        [EnumMember(Value = "BOOL")]
        BOOL = 6,

        /// <summary>
        /// Enum KEYWORDARRAY for value: KEYWORD_ARRAY
        /// </summary>
        [EnumMember(Value = "KEYWORD_ARRAY")]
        KEYWORDARRAY = 7
    }

}
