/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// SignalResult
    /// </summary>
    [DataContract(Name = "SignalResult")]
    public partial class SignalResult : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SignalRequestStatus
        /// </summary>
        [DataMember(Name = "signalRequestStatus", IsRequired = true, EmitDefaultValue = true)]
        public ChannelRequestStatus SignalRequestStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignalResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignalResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignalResult" /> class.
        /// </summary>
        /// <param name="commandId">commandId (required).</param>
        /// <param name="signalRequestStatus">signalRequestStatus (required).</param>
        /// <param name="signalChannelName">signalChannelName (required).</param>
        /// <param name="signalValue">signalValue.</param>
        public SignalResult(string commandId = default(string), ChannelRequestStatus signalRequestStatus = default(ChannelRequestStatus), string signalChannelName = default(string), EncodedObject signalValue = default(EncodedObject))
        {
            // to ensure "commandId" is required (not null)
            if (commandId == null)
            {
                throw new ArgumentNullException("commandId is a required property for SignalResult and cannot be null");
            }
            this.CommandId = commandId;
            this.SignalRequestStatus = signalRequestStatus;
            // to ensure "signalChannelName" is required (not null)
            if (signalChannelName == null)
            {
                throw new ArgumentNullException("signalChannelName is a required property for SignalResult and cannot be null");
            }
            this.SignalChannelName = signalChannelName;
            this.SignalValue = signalValue;
        }

        /// <summary>
        /// Gets or Sets CommandId
        /// </summary>
        [DataMember(Name = "commandId", IsRequired = true, EmitDefaultValue = true)]
        public string CommandId { get; set; }

        /// <summary>
        /// Gets or Sets SignalChannelName
        /// </summary>
        [DataMember(Name = "signalChannelName", IsRequired = true, EmitDefaultValue = true)]
        public string SignalChannelName { get; set; }

        /// <summary>
        /// Gets or Sets SignalValue
        /// </summary>
        [DataMember(Name = "signalValue", EmitDefaultValue = false)]
        public EncodedObject SignalValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignalResult {\n");
            sb.Append("  CommandId: ").Append(CommandId).Append("\n");
            sb.Append("  SignalRequestStatus: ").Append(SignalRequestStatus).Append("\n");
            sb.Append("  SignalChannelName: ").Append(SignalChannelName).Append("\n");
            sb.Append("  SignalValue: ").Append(SignalValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
