/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// TimerResult
    /// </summary>
    [DataContract(Name = "TimerResult")]
    public partial class TimerResult : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TimerStatus
        /// </summary>
        [DataMember(Name = "timerStatus", IsRequired = true, EmitDefaultValue = true)]
        public TimerStatus TimerStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TimerResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TimerResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TimerResult" /> class.
        /// </summary>
        /// <param name="commandId">commandId (required).</param>
        /// <param name="timerStatus">timerStatus (required).</param>
        public TimerResult(string commandId = default(string), TimerStatus timerStatus = default(TimerStatus))
        {
            // to ensure "commandId" is required (not null)
            if (commandId == null)
            {
                throw new ArgumentNullException("commandId is a required property for TimerResult and cannot be null");
            }
            this.CommandId = commandId;
            this.TimerStatus = timerStatus;
        }

        /// <summary>
        /// Gets or Sets CommandId
        /// </summary>
        [DataMember(Name = "commandId", IsRequired = true, EmitDefaultValue = true)]
        public string CommandId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TimerResult {\n");
            sb.Append("  CommandId: ").Append(CommandId).Append("\n");
            sb.Append("  TimerStatus: ").Append(TimerStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
