/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// TimerCommand
    /// </summary>
    [DataContract(Name = "TimerCommand")]
    public partial class TimerCommand : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimerCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TimerCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TimerCommand" /> class.
        /// </summary>
        /// <param name="commandId">commandId.</param>
        /// <param name="durationSeconds">durationSeconds (required).</param>
        public TimerCommand(string commandId = default(string), long durationSeconds = default(long))
        {
            this.DurationSeconds = durationSeconds;
            this.CommandId = commandId;
        }

        /// <summary>
        /// Gets or Sets CommandId
        /// </summary>
        [DataMember(Name = "commandId", EmitDefaultValue = false)]
        public string CommandId { get; set; }

        /// <summary>
        /// Gets or Sets DurationSeconds
        /// </summary>
        [DataMember(Name = "durationSeconds", IsRequired = true, EmitDefaultValue = true)]
        public long DurationSeconds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TimerCommand {\n");
            sb.Append("  CommandId: ").Append(CommandId).Append("\n");
            sb.Append("  DurationSeconds: ").Append(DurationSeconds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
