/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowStopRequest
    /// </summary>
    [DataContract(Name = "WorkflowStopRequest")]
    public partial class WorkflowStopRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets StopType
        /// </summary>
        [DataMember(Name = "stopType", EmitDefaultValue = false)]
        public WorkflowStopType? StopType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStopRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowStopRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStopRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="reason">reason.</param>
        /// <param name="stopType">stopType.</param>
        public WorkflowStopRequest(string workflowId = default(string), string workflowRunId = default(string), string reason = default(string), WorkflowStopType? stopType = default(WorkflowStopType?))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowStopRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            this.WorkflowRunId = workflowRunId;
            this.Reason = reason;
            this.StopType = stopType;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowStopRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  StopType: ").Append(StopType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
