/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines WorkflowConditionalCloseType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkflowConditionalCloseType
    {
        /// <summary>
        /// Enum FORCECOMPLETEONINTERNALCHANNELEMPTY for value: FORCE_COMPLETE_ON_INTERNAL_CHANNEL_EMPTY
        /// </summary>
        [EnumMember(Value = "FORCE_COMPLETE_ON_INTERNAL_CHANNEL_EMPTY")]
        FORCECOMPLETEONINTERNALCHANNELEMPTY = 1,

        /// <summary>
        /// Enum FORCECOMPLETEONSIGNALCHANNELEMPTY for value: FORCE_COMPLETE_ON_SIGNAL_CHANNEL_EMPTY
        /// </summary>
        [EnumMember(Value = "FORCE_COMPLETE_ON_SIGNAL_CHANNEL_EMPTY")]
        FORCECOMPLETEONSIGNALCHANNELEMPTY = 2,

        /// <summary>
        /// Enum GRACEFULCOMPLETEONALLCHANNELSEMPTY for value: GRACEFUL_COMPLETE_ON_ALL_CHANNELS_EMPTY
        /// </summary>
        [EnumMember(Value = "GRACEFUL_COMPLETE_ON_ALL_CHANNELS_EMPTY")]
        GRACEFULCOMPLETEONALLCHANNELSEMPTY = 3
    }

}
