/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines WorkflowStopType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkflowStopType
    {
        /// <summary>
        /// Enum CANCEL for value: CANCEL
        /// </summary>
        [EnumMember(Value = "CANCEL")]
        CANCEL = 1,

        /// <summary>
        /// Enum TERMINATE for value: TERMINATE
        /// </summary>
        [EnumMember(Value = "TERMINATE")]
        TERMINATE = 2,

        /// <summary>
        /// Enum FAIL for value: FAIL
        /// </summary>
        [EnumMember(Value = "FAIL")]
        FAIL = 3
    }

}
