/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowSignalRequest
    /// </summary>
    [DataContract(Name = "WorkflowSignalRequest")]
    public partial class WorkflowSignalRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSignalRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowSignalRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSignalRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="signalChannelName">signalChannelName (required).</param>
        /// <param name="signalValue">signalValue.</param>
        public WorkflowSignalRequest(string workflowId = default(string), string workflowRunId = default(string), string signalChannelName = default(string), EncodedObject signalValue = default(EncodedObject))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowSignalRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "signalChannelName" is required (not null)
            if (signalChannelName == null)
            {
                throw new ArgumentNullException("signalChannelName is a required property for WorkflowSignalRequest and cannot be null");
            }
            this.SignalChannelName = signalChannelName;
            this.WorkflowRunId = workflowRunId;
            this.SignalValue = signalValue;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets SignalChannelName
        /// </summary>
        [DataMember(Name = "signalChannelName", IsRequired = true, EmitDefaultValue = true)]
        public string SignalChannelName { get; set; }

        /// <summary>
        /// Gets or Sets SignalValue
        /// </summary>
        [DataMember(Name = "signalValue", EmitDefaultValue = false)]
        public EncodedObject SignalValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowSignalRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  SignalChannelName: ").Append(SignalChannelName).Append("\n");
            sb.Append("  SignalValue: ").Append(SignalValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
