/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowRpcRequest
    /// </summary>
    [DataContract(Name = "WorkflowRpcRequest")]
    public partial class WorkflowRpcRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowRpcRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowRpcRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowRpcRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="rpcName">rpcName (required).</param>
        /// <param name="input">input.</param>
        /// <param name="searchAttributesLoadingPolicy">searchAttributesLoadingPolicy.</param>
        /// <param name="dataAttributesLoadingPolicy">dataAttributesLoadingPolicy.</param>
        /// <param name="timeoutSeconds">timeoutSeconds.</param>
        /// <param name="useMemoForDataAttributes">useMemoForDataAttributes.</param>
        /// <param name="searchAttributes">searchAttributes.</param>
        public WorkflowRpcRequest(string workflowId = default(string), string workflowRunId = default(string), string rpcName = default(string), EncodedObject input = default(EncodedObject), PersistenceLoadingPolicy searchAttributesLoadingPolicy = default(PersistenceLoadingPolicy), PersistenceLoadingPolicy dataAttributesLoadingPolicy = default(PersistenceLoadingPolicy), int timeoutSeconds = default(int), bool useMemoForDataAttributes = default(bool), List<SearchAttributeKeyAndType> searchAttributes = default(List<SearchAttributeKeyAndType>))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowRpcRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "rpcName" is required (not null)
            if (rpcName == null)
            {
                throw new ArgumentNullException("rpcName is a required property for WorkflowRpcRequest and cannot be null");
            }
            this.RpcName = rpcName;
            this.WorkflowRunId = workflowRunId;
            this.Input = input;
            this.SearchAttributesLoadingPolicy = searchAttributesLoadingPolicy;
            this.DataAttributesLoadingPolicy = dataAttributesLoadingPolicy;
            this.TimeoutSeconds = timeoutSeconds;
            this.UseMemoForDataAttributes = useMemoForDataAttributes;
            this.SearchAttributes = searchAttributes;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets RpcName
        /// </summary>
        [DataMember(Name = "rpcName", IsRequired = true, EmitDefaultValue = true)]
        public string RpcName { get; set; }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [DataMember(Name = "input", EmitDefaultValue = false)]
        public EncodedObject Input { get; set; }

        /// <summary>
        /// Gets or Sets SearchAttributesLoadingPolicy
        /// </summary>
        [DataMember(Name = "searchAttributesLoadingPolicy", EmitDefaultValue = false)]
        public PersistenceLoadingPolicy SearchAttributesLoadingPolicy { get; set; }

        /// <summary>
        /// Gets or Sets DataAttributesLoadingPolicy
        /// </summary>
        [DataMember(Name = "dataAttributesLoadingPolicy", EmitDefaultValue = false)]
        public PersistenceLoadingPolicy DataAttributesLoadingPolicy { get; set; }

        /// <summary>
        /// Gets or Sets TimeoutSeconds
        /// </summary>
        [DataMember(Name = "timeoutSeconds", EmitDefaultValue = false)]
        public int TimeoutSeconds { get; set; }

        /// <summary>
        /// Gets or Sets UseMemoForDataAttributes
        /// </summary>
        [DataMember(Name = "useMemoForDataAttributes", EmitDefaultValue = true)]
        public bool UseMemoForDataAttributes { get; set; }

        /// <summary>
        /// Gets or Sets SearchAttributes
        /// </summary>
        [DataMember(Name = "searchAttributes", EmitDefaultValue = false)]
        public List<SearchAttributeKeyAndType> SearchAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowRpcRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  RpcName: ").Append(RpcName).Append("\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  SearchAttributesLoadingPolicy: ").Append(SearchAttributesLoadingPolicy).Append("\n");
            sb.Append("  DataAttributesLoadingPolicy: ").Append(DataAttributesLoadingPolicy).Append("\n");
            sb.Append("  TimeoutSeconds: ").Append(TimeoutSeconds).Append("\n");
            sb.Append("  UseMemoForDataAttributes: ").Append(UseMemoForDataAttributes).Append("\n");
            sb.Append("  SearchAttributes: ").Append(SearchAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
