/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowSkipTimerRequest
    /// </summary>
    [DataContract(Name = "WorkflowSkipTimerRequest")]
    public partial class WorkflowSkipTimerRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSkipTimerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowSkipTimerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSkipTimerRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="workflowStateExecutionId">workflowStateExecutionId (required).</param>
        /// <param name="timerCommandId">timerCommandId.</param>
        /// <param name="timerCommandIndex">timerCommandIndex.</param>
        public WorkflowSkipTimerRequest(string workflowId = default(string), string workflowRunId = default(string), string workflowStateExecutionId = default(string), string timerCommandId = default(string), int timerCommandIndex = default(int))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowSkipTimerRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "workflowStateExecutionId" is required (not null)
            if (workflowStateExecutionId == null)
            {
                throw new ArgumentNullException("workflowStateExecutionId is a required property for WorkflowSkipTimerRequest and cannot be null");
            }
            this.WorkflowStateExecutionId = workflowStateExecutionId;
            this.WorkflowRunId = workflowRunId;
            this.TimerCommandId = timerCommandId;
            this.TimerCommandIndex = timerCommandIndex;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowStateExecutionId
        /// </summary>
        [DataMember(Name = "workflowStateExecutionId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowStateExecutionId { get; set; }

        /// <summary>
        /// Gets or Sets TimerCommandId
        /// </summary>
        [DataMember(Name = "timerCommandId", EmitDefaultValue = false)]
        public string TimerCommandId { get; set; }

        /// <summary>
        /// Gets or Sets TimerCommandIndex
        /// </summary>
        [DataMember(Name = "timerCommandIndex", EmitDefaultValue = false)]
        public int TimerCommandIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowSkipTimerRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  WorkflowStateExecutionId: ").Append(WorkflowStateExecutionId).Append("\n");
            sb.Append("  TimerCommandId: ").Append(TimerCommandId).Append("\n");
            sb.Append("  TimerCommandIndex: ").Append(TimerCommandIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
