/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowGetDataObjectsRequest
    /// </summary>
    [DataContract(Name = "WorkflowGetDataObjectsRequest")]
    public partial class WorkflowGetDataObjectsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowGetDataObjectsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowGetDataObjectsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowGetDataObjectsRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="keys">keys.</param>
        /// <param name="useMemoForDataAttributes">useMemoForDataAttributes.</param>
        public WorkflowGetDataObjectsRequest(string workflowId = default(string), string workflowRunId = default(string), List<string> keys = default(List<string>), bool useMemoForDataAttributes = default(bool))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowGetDataObjectsRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            this.WorkflowRunId = workflowRunId;
            this.Keys = keys;
            this.UseMemoForDataAttributes = useMemoForDataAttributes;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets Keys
        /// </summary>
        [DataMember(Name = "keys", EmitDefaultValue = false)]
        public List<string> Keys { get; set; }

        /// <summary>
        /// Gets or Sets UseMemoForDataAttributes
        /// </summary>
        [DataMember(Name = "useMemoForDataAttributes", EmitDefaultValue = true)]
        public bool UseMemoForDataAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowGetDataObjectsRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  UseMemoForDataAttributes: ").Append(UseMemoForDataAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
