/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// Defines WorkflowResetType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkflowResetType
    {
        /// <summary>
        /// Enum HISTORYEVENTID for value: HISTORY_EVENT_ID
        /// </summary>
        [EnumMember(Value = "HISTORY_EVENT_ID")]
        HISTORYEVENTID = 1,

        /// <summary>
        /// Enum BEGINNING for value: BEGINNING
        /// </summary>
        [EnumMember(Value = "BEGINNING")]
        BEGINNING = 2,

        /// <summary>
        /// Enum HISTORYEVENTTIME for value: HISTORY_EVENT_TIME
        /// </summary>
        [EnumMember(Value = "HISTORY_EVENT_TIME")]
        HISTORYEVENTTIME = 3,

        /// <summary>
        /// Enum STATEID for value: STATE_ID
        /// </summary>
        [EnumMember(Value = "STATE_ID")]
        STATEID = 4,

        /// <summary>
        /// Enum STATEEXECUTIONID for value: STATE_EXECUTION_ID
        /// </summary>
        [EnumMember(Value = "STATE_EXECUTION_ID")]
        STATEEXECUTIONID = 5
    }

}
