/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowConditionalClose
    /// </summary>
    [DataContract(Name = "WorkflowConditionalClose")]
    public partial class WorkflowConditionalClose : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ConditionalCloseType
        /// </summary>
        [DataMember(Name = "conditionalCloseType", EmitDefaultValue = false)]
        public WorkflowConditionalCloseType? ConditionalCloseType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowConditionalClose" /> class.
        /// </summary>
        /// <param name="conditionalCloseType">conditionalCloseType.</param>
        /// <param name="channelName">channelName.</param>
        /// <param name="closeInput">closeInput.</param>
        public WorkflowConditionalClose(WorkflowConditionalCloseType? conditionalCloseType = default(WorkflowConditionalCloseType?), string channelName = default(string), EncodedObject closeInput = default(EncodedObject))
        {
            this.ConditionalCloseType = conditionalCloseType;
            this.ChannelName = channelName;
            this.CloseInput = closeInput;
        }

        /// <summary>
        /// Gets or Sets ChannelName
        /// </summary>
        [DataMember(Name = "channelName", EmitDefaultValue = false)]
        public string ChannelName { get; set; }

        /// <summary>
        /// Gets or Sets CloseInput
        /// </summary>
        [DataMember(Name = "closeInput", EmitDefaultValue = false)]
        public EncodedObject CloseInput { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowConditionalClose {\n");
            sb.Append("  ConditionalCloseType: ").Append(ConditionalCloseType).Append("\n");
            sb.Append("  ChannelName: ").Append(ChannelName).Append("\n");
            sb.Append("  CloseInput: ").Append(CloseInput).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
