/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowDumpRequest
    /// </summary>
    [DataContract(Name = "WorkflowDumpRequest")]
    public partial class WorkflowDumpRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowDumpRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowDumpRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowDumpRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId (required).</param>
        /// <param name="pageSizeInBytes">pageSizeInBytes (required).</param>
        /// <param name="pageNum">pageNum (required).</param>
        public WorkflowDumpRequest(string workflowId = default(string), string workflowRunId = default(string), int pageSizeInBytes = default(int), int pageNum = default(int))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowDumpRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "workflowRunId" is required (not null)
            if (workflowRunId == null)
            {
                throw new ArgumentNullException("workflowRunId is a required property for WorkflowDumpRequest and cannot be null");
            }
            this.WorkflowRunId = workflowRunId;
            this.PageSizeInBytes = pageSizeInBytes;
            this.PageNum = pageNum;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets PageSizeInBytes
        /// </summary>
        [DataMember(Name = "pageSizeInBytes", IsRequired = true, EmitDefaultValue = true)]
        public int PageSizeInBytes { get; set; }

        /// <summary>
        /// Gets or Sets PageNum
        /// </summary>
        [DataMember(Name = "pageNum", IsRequired = true, EmitDefaultValue = true)]
        public int PageNum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowDumpRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  PageSizeInBytes: ").Append(PageSizeInBytes).Append("\n");
            sb.Append("  PageNum: ").Append(PageNum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
