/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowResetRequest
    /// </summary>
    [DataContract(Name = "WorkflowResetRequest")]
    public partial class WorkflowResetRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ResetType
        /// </summary>
        [DataMember(Name = "resetType", IsRequired = true, EmitDefaultValue = true)]
        public WorkflowResetType ResetType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResetRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowResetRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResetRequest" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="workflowRunId">workflowRunId.</param>
        /// <param name="resetType">resetType (required).</param>
        /// <param name="historyEventId">historyEventId.</param>
        /// <param name="reason">reason.</param>
        /// <param name="historyEventTime">historyEventTime.</param>
        /// <param name="stateId">stateId.</param>
        /// <param name="stateExecutionId">stateExecutionId.</param>
        /// <param name="skipSignalReapply">skipSignalReapply.</param>
        /// <param name="skipUpdateReapply">skipUpdateReapply.</param>
        public WorkflowResetRequest(string workflowId = default(string), string workflowRunId = default(string), WorkflowResetType resetType = default(WorkflowResetType), int historyEventId = default(int), string reason = default(string), string historyEventTime = default(string), string stateId = default(string), string stateExecutionId = default(string), bool skipSignalReapply = default(bool), bool skipUpdateReapply = default(bool))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for WorkflowResetRequest and cannot be null");
            }
            this.WorkflowId = workflowId;
            this.ResetType = resetType;
            this.WorkflowRunId = workflowRunId;
            this.HistoryEventId = historyEventId;
            this.Reason = reason;
            this.HistoryEventTime = historyEventTime;
            this.StateId = stateId;
            this.StateExecutionId = stateExecutionId;
            this.SkipSignalReapply = skipSignalReapply;
            this.SkipUpdateReapply = skipUpdateReapply;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowRunId
        /// </summary>
        [DataMember(Name = "workflowRunId", EmitDefaultValue = false)]
        public string WorkflowRunId { get; set; }

        /// <summary>
        /// Gets or Sets HistoryEventId
        /// </summary>
        [DataMember(Name = "historyEventId", EmitDefaultValue = false)]
        public int HistoryEventId { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets HistoryEventTime
        /// </summary>
        [DataMember(Name = "historyEventTime", EmitDefaultValue = false)]
        public string HistoryEventTime { get; set; }

        /// <summary>
        /// Gets or Sets StateId
        /// </summary>
        [DataMember(Name = "stateId", EmitDefaultValue = false)]
        public string StateId { get; set; }

        /// <summary>
        /// Gets or Sets StateExecutionId
        /// </summary>
        [DataMember(Name = "stateExecutionId", EmitDefaultValue = false)]
        public string StateExecutionId { get; set; }

        /// <summary>
        /// Gets or Sets SkipSignalReapply
        /// </summary>
        [DataMember(Name = "skipSignalReapply", EmitDefaultValue = true)]
        public bool SkipSignalReapply { get; set; }

        /// <summary>
        /// Gets or Sets SkipUpdateReapply
        /// </summary>
        [DataMember(Name = "skipUpdateReapply", EmitDefaultValue = true)]
        public bool SkipUpdateReapply { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowResetRequest {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  WorkflowRunId: ").Append(WorkflowRunId).Append("\n");
            sb.Append("  ResetType: ").Append(ResetType).Append("\n");
            sb.Append("  HistoryEventId: ").Append(HistoryEventId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  HistoryEventTime: ").Append(HistoryEventTime).Append("\n");
            sb.Append("  StateId: ").Append(StateId).Append("\n");
            sb.Append("  StateExecutionId: ").Append(StateExecutionId).Append("\n");
            sb.Append("  SkipSignalReapply: ").Append(SkipSignalReapply).Append("\n");
            sb.Append("  SkipUpdateReapply: ").Append(SkipUpdateReapply).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
