/*
 * Workflow APIs
 *
 * This APIs for iwf SDKs to operate workflows
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IwfDotnetSdk.ApiClients.Client.OpenAPIDateConverter;

namespace IwfDotnetSdk.ApiClients.Model
{
    /// <summary>
    /// WorkflowAlreadyStartedOptions
    /// </summary>
    [DataContract(Name = "WorkflowAlreadyStartedOptions")]
    public partial class WorkflowAlreadyStartedOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowAlreadyStartedOptions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowAlreadyStartedOptions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowAlreadyStartedOptions" /> class.
        /// </summary>
        /// <param name="ignoreAlreadyStartedError">ignoreAlreadyStartedError (required).</param>
        /// <param name="requestId">requestId.</param>
        public WorkflowAlreadyStartedOptions(bool ignoreAlreadyStartedError = default(bool), string requestId = default(string))
        {
            this.IgnoreAlreadyStartedError = ignoreAlreadyStartedError;
            this.RequestId = requestId;
        }

        /// <summary>
        /// Gets or Sets IgnoreAlreadyStartedError
        /// </summary>
        [DataMember(Name = "ignoreAlreadyStartedError", IsRequired = true, EmitDefaultValue = true)]
        public bool IgnoreAlreadyStartedError { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [DataMember(Name = "requestId", EmitDefaultValue = false)]
        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowAlreadyStartedOptions {\n");
            sb.Append("  IgnoreAlreadyStartedError: ").Append(IgnoreAlreadyStartedError).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
